# docker network create my_network
version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: foundation
      POSTGRES_PASSWORD: foundation_5227
      POSTGRES_DB: nest_foundation
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_5227
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    networks:
      - my_network

  nest-app:
    build: .
    container_name: nest-app
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: foundation
      DATABASE_PASSWORD: foundation_5227
      DATABASE_NAME: nest_foundation
      DATABASE_PREFIX: nf_
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio_5227
      MINIO_REGION: ap-northeast-2 # AWS Region SEOUL
      MINIO_BUCKET_PREFIX: nf_
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - minio
    networks:
      - my_network
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
  minio_data:

networks:
  my_network:
    external: true
